# PinAPLPy: Platform-independent Analysis of Pooled Screens using Python
# P. Spahn et al., UC San Diego (10/2016) 

# ***********************************************************************
# CONFIGURATION FILE
# ***********************************************************************

# PROJECT PARAMETERS
ScreenType: 'enrichment'                    # type of screen ['enrichment'/'depletion']
LibFilename: 'GeCKOv2_library.tsv'            # filename of library spreadsheet  
seq_5_end: 'TCTTGTGGAAAGGACGAAACACCG'       # sequence 5' of sgRNA in read
seq_3_end: 'GTTTTAGAGCTAGAAATAGCAAGTT'       # sequence 3' of sgRNA in read

# ANALYSIS OPTIONS
AlnOutput: 'Compress'                  # keep raw alignment output? ['Keep'/'Compress'/'Delete']
keepCutReads: False                    # keep files containing trimmed reads? ['True'/'False']
Normalization: 'cpm'                  # Normalization of read counts (counts per mio reads / size-factor) ['cpm'/'size']
Cutoff: 0                           # set counts (cpm) below this number to 0 
GeneMetric: 'aRRA'                    # metric for gene ranking ['aRRA'/'STARS'/'ES']
Np: 1000                         # number of permutations for gene ranking analysis 
thr_STARS: 10                          # Threshold percentage for STARS analysis
scatter_annotate: False                 # annotate scatterplot with sgRNA IDs? ['True'/'False']
ClusterBy: 'counts'                  # clustering criterion ['variance'/'counts']
TopN: 25                              # number of top sgRNAs to take into account for clustering
HitListFormat: 'tsv'                  # Format of results spreadsheets (sgRNA hits and gene ranking) ['tsv'/'xlsx']
NonTargetPrefix: 'NonTargeting'        # prefix for non-targeting sgRNAs in library (keep at default if none present)

# TECHNICAL PARAMETERS
CutErrorTol: 0.25                       # Cutadapt error tolerance
R_min:  10                             # minimal required read length after cutadapt trimming
L_bw: 11                               # Bowtie2 -L parameter (seed length)
N_bw: 1                                # Bowtie2 -N parameter (seed mismatch)
i_bw: 'S,1,0.75'                       # Bowtie2 -i parameter (interval function)
Theta: 2                               # alignment ambiguity tolerance
max_q: 95                              # maximum quantile for histogram plots
alpha: 0.01                            # significance level    
padj: 'fdr_bh'                        # method for p-value adjustment ['fdr_bh'/'fdr_tsbh']
sgRNAsPerGene: 6                       # number of sgRNAs targeting each gene (excluding non-targeting controls and miRNAs). 
                                       #    ONLY IMPORTANT IF 'ES' is chosen for gene ranking method !

delta_d: 0.01                         # count shift for computing fold changes and size-factors (avoid division by zero)
delta_2: 1                              # count shift cases of zeros in control count variance (avoid division by zero)
delta_s: 0.1                         # count shift before log transformation in scatterplots
delta_p: 1                             # count shift before log transformation in heatmap

# VISUALIZATION PARAMETERS
dpi: 300                               # resolution of PNG plots
svg: False                              # save figures as vector graphics?  ['True'/'False']            
dotsize: 10                            # size of dots in scatterplot
logbase: 10                            # base for log transformation of counts in scatterplots
width_p: 800                            # width of heatmap image (pixels)
height_p: 800                            # height of heatmap image (pixels)
fontsize_p: 14                          # fontsize in heatmap image
marginsize: 7                           # size of margin in heatmap image (increase if sample names are clipped)

# DIRECTORIES
WorkingDir: '/home/philipp/Documents/Projects/PinAPL-Py/'
DataDir: '/home/philipp/Documents/Projects/PinAPL-Py/Data/'
LibDir: '/home/philipp/Documents/Projects/PinAPL-Py/Library/'
IndexDir: '/home/philipp/Documents/Projects/PinAPL-Py/Library/Bowtie2_Index/'
ScriptsDir: '/home/philipp/Documents/Projects/PinAPL-Py/Scripts/'
AlignDir: '/home/philipp/Documents/Projects/PinAPL-Py/Alignments/'
AnalysisDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/'
HitDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/sgRNA_Rankings'
GeneDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Gene_Rankings'
ControlDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Control/'
HeatDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Heatmap/'
AlnQCDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Alignment_Statistics/'
CountQCDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/ReadCount_Statistics/'
ScatterDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/ReadCount_Scatterplots/'
CorrelDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Replicate_Correlation/'
EffDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/sgRNA_Efficiency/'
DepthDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Read_Depth/' 
pvalDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/p-values/' 
bw2Dir: '/home/philipp/Programs/bowtie2-2.2.8/'
CutAdaptDir: '/home/philipp/Programs/cutadapt/'   
STARSDir: '/home/philipp/Documents/Projects/Python/STARS_v1.2/'


# SCRIPT FILENAMES
script00: 'BuildLibraryIndex'
script01: 'LoadDataSheet'
script02: 'PlotNumReads'
script03: 'AlignReads'
script04: 'NormalizeReadCounts'
script05: 'AnalyzeReadCounts'
script06: 'AnalyzeControl'
script07: 'FindHits'
script08: 'RankGenes'
script09: 'PlotCounts'
script10: 'PlotReplicates'
script11: 'PlotHeatmap'


