# PinAPLPy: Platform-independent Analysis of Pooled Screens using Python
# P. Spahn et al., UC San Diego (10/2016) 

# ***********************************************************************
# CONFIGURATION FILE
# ***********************************************************************

# PROJECT PARAMETERS
ScreenType: 'depletion'                    # type of screen ['enrichment'/'depletion']
LibFilename: 'GeCKOv2_Mouse.csv'            # filename of library spreadsheet  
seq_5_end: 'TCTTGTGGAAAGGACGAAACACCG'       # sequence 5' of sgRNA in read
seq_3_end: 'GTTTTAGAGCTAGAAATAGCAAGTT'       # sequence 3' of sgRNA in read
NonTargetPrefix: 'NonTargeting'             # prefix for non-targeting sgRNAs in library (keep at default if none present)
sgRNAsPerGene: 6                       # number of sgRNAs targeting each gene (excluding non-targeting controls and miRNAs). 
                                       #    ONLY IMPORTANT IF 'ES' is chosen for gene ranking method !

# ANALYSIS OPTIONS
AlnOutput: 'Delete'                  # keep raw alignment output? ['Keep'/'Compress'/'Delete']
keepCutReads: False                    # keep files containing trimmed reads? ['True'/'False']
VarEst: 'model'                        # method for count variance estimation ['model'/'sample')]
GeneMetric: 'aRRA'                    # metric for gene ranking ['aRRA'/'STARS'/'ES']
scatter_annotate: False                 # annotate scatterplot with sgRNA IDs? ['True'/'False']
ClusterBy: 'variance'                  # clustering criterion ['variance'/'counts']
TopN: 25                              # number of top sgRNAs to take into account for clustering
HitListFormat: 'tsv'                  # Format of results spreadsheets (sgRNA hits and gene ranking) ['tsv'/'xlsx']

# TECHNICAL PARAMETERS
CutErrorTol: 0.25                       # Cutadapt error tolerance
R_min:  10                             # minimal required read length after cutadapt trimming
L_bw: 11                               # Bowtie2 -L parameter (seed length)
N_bw: 1                                # Bowtie2 -N parameter (seed mismatch)
i_bw: 'S,1,0.75'                       # Bowtie2 -i parameter (interval function)
Theta: 2                               # alignment ambiguity tolerance
max_q: 95                              # maximum quantile for histogram plots
alpha: 0.01                            # significance level    
pcorr: 'fdr_bh'                        # method for p-value correction ['fdr_bh'/'fdr_tsbh']
Np_ES: 10                             # number of permutations for gene ranking analysis (ES)
Np_aRRA: 100                         # number of permutations for gene ranking analysis (aRRA)
Np_STARS: 10                          # number of permutations for gene ranking analysis (STARS)
thr_STARS: 10                          # Threshold percentage for STARS analysis
delta_d: 0.01                         # count shift for computing fold changes (avoid division by zero)


# VISUALIZATION PARAMETERS
# Scatterplots
dpi: 300                               # resolution of PNG plots
delta_s: 0.1                         # count shift before log transformation in scatterplots
dotsize: 10                            # size of dots in scatterplot
logbase: 10                            # base for log transformation of counts in scatterplots
# Heatmap
delta_p: 1                             # count shift before log transformation in heatmap
width_p: 800                            # width of heatmap image (pixels)
height_p: 800                            # height of heatmap image (pixels)
fontsize_p: 14                          # fontsize in heatmap image
marginsize: 7                           # size of margin in heatmap image (increase if sample names are clipped)

# DIRECTORIES
WorkingDir: '/home/philipp/Documents/Projects/PinAPL-Py/'
DataDir: '/home/philipp/Documents/Projects/PinAPL-Py/Data/'
LibDir: '/home/philipp/Documents/Projects/PinAPL-Py/Library/'
IndexDir: '/home/philipp/Documents/Projects/PinAPL-Py/Library/Bowtie2_Index/'
ScriptsDir: '/home/philipp/Documents/Projects/PinAPL-Py/Scripts/'
AlignDir: '/home/philipp/Documents/Projects/PinAPL-Py/Alignments/'
AnalysisDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/'
HitDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Hit Lists'
GeneDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Gene Rankings'
ControlDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Control/'
HeatDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Heatmap/'
QCDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/QC/'
ScatterDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Scatterplots/'
EffDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/sgRNA Efficiency/'
DepthDir: '/home/philipp/Documents/Projects/PinAPL-Py/Analysis/Read Depth/' 
bw2Dir: '/home/philipp/Programs/bowtie2-2.2.8/'
CutAdaptDir: '/home/philipp/Programs/cutadapt/'   
STARSDir: '/home/philipp/Documents/Projects/Python/STARS_v1.2/'

# SCRIPT FILENAMES
script00: 'BuildLibraryIndex'
script01: 'AlignReads'
script02: 'AnalyzeReadCounts'
script03: 'AnalyzeControl'
script04: 'FindHits'
script05: 'RankGenes'
script06: 'PlotCounts'
script07: 'PlotReplicates'
script08: 'PlotHeatmap'


